spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  profiles:
    active: dev

---

spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    hibernate: 
      ddl-auto: update

---

spring:
  profiles: prod
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
